### ISSUE TITLE
Anubis issues

### ISSUE THREAD

**Issue by artrain112** [Catterall/discord-raidkit#13]
Human. There has been an error attempting to run anubis. The following measures may solve the issue:

-The PostgreSQL master password specified may be incorrect - perhaps do a double-take?
-The bot prefix specified may be invalid - a prefix must be provided in order to use the bot's commands.
-The bot token specified may be incorrect - try regenerating a new bot token and use that token instead.
-If the settings file is missing, try running the program again. If the issue persists, view the GitHub page.
-If the settings file is perfect, check whether you have enabled Privallged Gateway Intents on your bot's page.

If the issue persists after all the above measures are taken, you can create an issue here:
https://github.com/Catterall/discord-raidkit/issues

Thank you for using Anubis and apologies for all errors encountered! -Catterall. 

i have followed the postgresql tutorial for anubis, made the bot and also installed the requirements. I believe it maybe the privalleged gateway intent, but i dont know how to enable, but if you can help pls reply

**Comment by Catterall** [comment]
On the new version I'll include the exception in the default error message.
