### ISSUE TITLE
Osiris : Chromedriver.exe

### ISSUE THREAD

**Issue by ResolutePSD** [Catterall/discord-raidkit#15]
I have made sure to follow all required steps for installation of chromedriver.exe. Though I am on Mac, I had a look at the configuration files and code and it doesn't appear to me that it would make a difference.
![Screen Shot 2021-03-08 at 11 49 08 PM](https://user-images.githubusercontent.com/78404092/110373977-89fe5500-8069-11eb-8f1c-81cfdddf9b17.png)

**Comment by ResolutePSD** [comment]
Update!: I simply just had to fix the pathing as my Mac needs specific paths, not just the file name. However, when I write the correct path it says "Permission Denied", but if I replaced it with the old pathing, it runs the program. Is there a set of executable permissions that need to be configured in Chromedriver.exe?

**Comment by Catterall** [comment]
Closing: presumed fix; author inactive.

**Comment by the-cult-of-integral** [comment]
Update: would've likely been the browser folder not placed in the correct location. Issue invalid.
