### ISSUE TITLE
Nothing is Opening.

### ISSUE THREAD

**Issue by NBTCommunity** [Catterall/discord-raidkit#20]
I'm trying to run Anubis but when I open main.py nothing happens. It opens it but closes a second later. I did everything in your guide and video nothing is happening. Please help.

**Comment by NBTCommunity** [comment]
> Open it via CMD and tell me the error.

I'm running **python main.py** in cmd is that how I do it? I'm sorry I've only used a few scripts and nothing like this.

**Comment by Catterall** [comment]
Run python main.py in CMD and tell me the error that is returned.

**Comment by NBTCommunity** [comment]
**python: can't open file 'C:\Users\The_N\main.py': [Errno 2] No such file or directory**

Did I do something wrong with the Path? I installed python and checked the box so I don't know what is happening.

**Comment by Catterall** [comment]
Here's the problem:

There is no main.py file in the directory that you're attempting to run the file. I'm afraid can't help you with basic general knowledge, e.g. how to run a file, so please refrain from making issues again unless there is an issue with the program, not with your competence.

Apologies.
