### ISSUE TITLE
Are there versions of these that grab/log on MacOS?

### ISSUE THREAD

**Issue by AstroOrbis** [Catterall/discord-raidkit#22]

**Comment by ytsix** [comment]
Hey there, (one of the devs that contributed to this), Some of these could work on MacOS, but then again most of these were made by Windows Users for Windows, have a good one!

**Comment by Catterall** [comment]
Thanks, ytsix is my pet.

**Comment by AstroOrbis** [comment]
thanks yall! I'll try and contribute a system that checks OS and adjusts paths accordingly :3
