### ISSUE TITLE
File just closes when opening.

### ISSUE THREAD

**Issue by xCancazedd** [Catterall/discord-raidkit#26]
I'm trying to use Osiris but when I open the main.py file it just closes. I have Python 3.8.0.

**Comment by poiper** [comment]
if you don't mind could you please run the file and reply to to this message with the error message so I can get greater detail on why your file is just closing.

**Comment by EFLYT** [comment]
> if you don't mind could you please run the file and reply to to this message with the error message so I can get greater detail on why your file is just closing.

Hello i'm getting a similar error and this is what shows up. (Sorry for transparent image, it was a bit hard to get a screenshot of it.)
![error](https://user-images.githubusercontent.com/69177140/129486370-c6273456-0c88-4abe-9d27-8d75ab8a8a3b.png)

**Comment by znqi** [comment]
> > if you don't mind could you please run the file and reply to to this message with the error message so I can get greater detail on why your file is just closing.
> 
> Hello i'm getting a similar error and this is what shows up. (Sorry for transparent image, it was a bit hard to get a screenshot of it.)
> ![error](https://user-images.githubusercontent.com/69177140/129486370-c6273456-0c88-4abe-9d27-8d75ab8a8a3b.png)

There is a missing module in order to run the program. Use `pip install requests` to install the necessary module. Also, I recommend running the python program on your terminal instead of running on a python shell since it will just close and open.

**Comment by znqi** [comment]
> I'm trying to use Osiris but when I open the main.py file it just closes. I have Python 3.8.0.

Make sure necessary modules are installed correctly.

**Comment by znqi** [comment]
Oh, I saw the repo owner already added auto-installation of the requirements. Just run the [install_requirements.cmd](https://github.com/Catterall/discord-raidkit/blob/master/install_requirements.cmd)
