### ISSUE TITLE
Can't run Osiris

### ISSUE THREAD

**Issue by Zumodenaranja739** [Catterall/discord-raidkit#4]
The python instantly closes, and I also tried using it with cmd but cant, i selected install to PATH.
![unknown](https://user-images.githubusercontent.com/55620434/100552052-01f7fa80-3285-11eb-8733-b8370f44d0bb.png)

**Comment by Catterall** [comment]
English: Have you tried running the `install_requirements.cmd` file?
Portuguese: Você já tentou executar o arquivo `install_requirements.cmd`?

**Comment by Zumodenaranja739** [comment]
Yes, more than once

**Comment by Catterall** [comment]
OK, add me on discord: Catterall##7872

**Comment by Catterall** [comment]
Currently resolving via discord - looks like a one off issue (closed) with PIP.
