### ISSUE TITLE
Anubis saying the settings are incorrect

### ISSUE THREAD

**Issue by Dannyboi14** [Catterall/discord-raidkit#6]
so its not my first time using this but now for some reasons after the update I filled everything in but the bot is saying my settings are incorrect any ideas?

**Comment by Catterall** [comment]
Could you send more specific information to Catterall#7872 - Also, have you made sure to read the updated readme.md? Not saying it would work, but it may work.

**Comment by Catterall** [comment]
Should be fixed in v1.3.4.
