### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Qzo1s** [Catterall/discord-raidkit#9]
Human. There has been an error attempting to run Qetesh. The following measures may solve the issue:

-The bot prefix specified may be invalid - a prefix must be provided in order to use the bot's commands.
-The bot token specified may be incorrect - try regenerating a new bot token and use that token instead.
-If the settings file is missing, try running the program again. If the issue persists, view the GitHub page.
-If the settings file is perfect, check whether you have enabled Privallged Gateway Intents on your bot's page.

**Comment by Catterall** [comment]
Did you follow the error message through?

**Comment by Qzo1s** [comment]
yes

**Comment by Catterall** [comment]
xSerpentine#7872 Add me on discord.

**Comment by itsr3d3y3s** [comment]
same issue, any fixes?

**Comment by Catterall** [comment]
Resolved; issue unknown.
